paths:
  raw_data: data/raw/panama_road_incidents
  recommendation_data: data/raw/social_media_preferences.csv
  sentiment_data: data/raw/spanish_tweet_sentiment.csv
  processed_train: data/processed/train.csv
  processed_test: data/processed/test.csv
  model_artifact: artifacts/text_classifier.joblib
split:
  test_size: 0.2
  random_state: 42
model:
  max_features: 5000
  C: 1.0
  n_neurons: 0
logging:
  level: INFO
recommender:
  demographics:
    age_segments:
      - label: "under-18"
        max: 17
      - label: "18-24"
        min: 18
        max: 24
      - label: "25-34"
        min: 25
        max: 34
      - label: "35-44"
        min: 35
        max: 44
      - label: "45-54"
        min: 45
        max: 54
      - label: "55+"
        min: 55
maps:
  google_api_key: ""
