paths:
  raw_data: data/raw/panama_road_incidents
  recommendation_data: data/raw/social_media_preferences.csv
  sentiment_data: data/raw/spanish_tweet_sentiment.csv
  processed_train: data/processed/train.csv
  processed_test: data/processed/test.csv
  model_artifact: artifacts/text_classifier.joblib
text_preprocessing:
  stopword_exclusions:
    - no
    - sin
    - ni
    - nunca
    - nadie
    - ninguno
    - ninguna
split:
  test_size: 0.2
  random_state: 42
model:
  max_features: 8000
  C: 1.5
  n_neurons: 0
  ngram_range:
    - 1
    - 2
  stopword_exclusions:
    - no
    - sin
    - ni
    - nunca
sentiment_model:
  max_features: 6000
  C: 2.0
  ngram_range:
    - 1
    - 2
  stopword_exclusions:
    - no
    - sin
    - ni
  label_aliases:
    powerful: "motivación y superación"
    mad: "frustración"
    peaceful: "tranquilidad"
    joyful: "alegría"
    sad: "tristeza"
    scared: "temor"
  emotion_aliases:
    confident: "confianza"
    relaxed: "relajado"
    overwhelmed: "abrumado"
    frustrated: "frustración"
category_rules:
  keyword_overrides:
    - category: "obstaculo"
      patterns:
        - "escombro"
        - "escombros"
        - "poste caido"
        - "poste caído"
        - "arbol caido"
        - "arbol caído"
        - "vehiculo varado"
        - "vehiculo averiado"
        - "camion varado"
        - "derrumb"
        - "bloqueo"
        - "obstaculo"
        - "obstaculo en via"
        - "material en la via"
    - category: "informativo"
      patterns:
        - "sin accidente"
        - "sin accidentes"
        - "sin incidentes"
        - "sin novedades"
        - "no se reportan accidentes"
        - "no se reportan incidentes"
        - "no se reportan heridos"
        - "no hubo accidentes"
        - "no registra accidentes"
logging:
  level: INFO
recommender:
  demographics:
    age_segments:
      - label: "under-18"
        max: 17
      - label: "18-24"
        min: 18
        max: 24
      - label: "25-34"
        min: 25
        max: 34
      - label: "35-44"
        min: 35
        max: 44
      - label: "45-54"
        min: 45
        max: 54
      - label: "55+"
        min: 55
maps:
  google_api_key: ""
n_suggestions: 5
top_keywords: 5
